### ISSUE TITLE
[`Bug`] : Facing `FileNotFoundError`

### ISSUE THREAD

**Issue by baseplate-admin** [adamchainz/django-watchfiles#12]
Hi there,

Thank you very much for creating this awesome replacement for watchman
I am facing an error. Where i cant run the project under pipenv and django. 

Repository link : https://github.com/baseplate-admin/CoreProject/tree/540f8e030cf54a865c962bd7e886b76948ccb65c/backend

Python version : 3.11.1

<details>
<summary>
StackTrace : 
</summary>

```python
PS C:\Users\Asus\Desktop\CoreProject\backend> pipenv run python .\django_core\manage.py runserver 
Watching for file changes with WatchfilesReloader
Performing system checks...

System check identified no issues (0 silenced).
December 15, 2022 - 16:14:12
Django version 4.1.4, using settings 'core.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Traceback (most recent call last):
  File "C:\Users\Asus\Desktop\CoreProject\backend\django_core\manage.py", line 22, in <module>
    main()
  File "C:\Users\Asus\Desktop\CoreProject\backend\django_core\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Asus\.virtualenvs\backend-FjxXGjsR\Lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "C:\Users\Asus\.virtualenvs\backend-FjxXGjsR\Lib\site-packages\django\core\management\__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Asus\.virtualenvs\backend-FjxXGjsR\Lib\site-packages\django\core\management\base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Asus\.virtualenvs\backend-FjxXGjsR\Lib\site-packages\django\core\management\commands\runserver.py", line 74, in execute
    super().execute(*args, **options)
  File "C:\Users\Asus\.virtualenvs\backend-FjxXGjsR\Lib\site-packages\django\core\management\base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\.virtualenvs\backend-FjxXGjsR\Lib\site-packages\django\core\management\commands\runserver.py", line 111, in handle
    self.run(**options)
  File "C:\Users\Asus\.virtualenvs\backend-FjxXGjsR\Lib\site-packages\django\core\management\commands\runserver.py", line 118, in run
    autoreload.run_with_reloader(self.inner_run, **options)
  File "C:\Users\Asus\.virtualenvs\backend-FjxXGjsR\Lib\site-packages\django\utils\autoreload.py", line 680, in run_with_reloader
    start_django(reloader, main_func, *args, **kwargs)
  File "C:\Users\Asus\.virtualenvs\backend-FjxXGjsR\Lib\site-packages\django\utils\autoreload.py", line 661, in start_django
    reloader.run(django_main_thread)
  File "C:\Users\Asus\.virtualenvs\backend-FjxXGjsR\Lib\site-packages\django\utils\autoreload.py", line 344, in run
    self.run_loop()
  File "C:\Users\Asus\.virtualenvs\backend-FjxXGjsR\Lib\site-packages\django\utils\autoreload.py", line 350, in run_loop
    next(ticker)
  File "C:\Users\Asus\.virtualenvs\backend-FjxXGjsR\Lib\site-packages\django_watchfiles\__init__.py", line 21, in tick
    for file_changes in watcher:
  File "C:\Users\Asus\.virtualenvs\backend-FjxXGjsR\Lib\site-packages\watchfiles\main.py", line 119, in watch
    with RustNotify([str(p) for p in paths], debug, force_polling, poll_delay_ms, recursive) as watcher:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: Input watch path is neither a file nor a directory.
```

</details>

**Comment by adamchainz** [comment]
Can you debug the value of `roots` being passed to watchfiles in `WatchFileReloader.tick()` ?

**Comment by baseplate-admin** [comment]
So i have modified this file to get the Root value 

<details>
<summary>Modified Python Code :</summary>

```python
from __future__ import annotations

from pathlib import Path
from typing import Generator

import watchfiles
from django.utils import autoreload
import sys
from pprint import pprint


class WatchfilesReloader(autoreload.BaseReloader):
    def watched_roots(self, watched_files: list[Path]) -> frozenset[Path]:
        extra_directories = self.directory_globs.keys()
        watched_file_dirs = {f.parent for f in watched_files}
        sys_paths = set(autoreload.sys_path_directories())
        return frozenset((*extra_directories, *watched_file_dirs, *sys_paths))

    def tick(self) -> Generator[None, None, None]:
        watched_files = list(self.watched_files(include_globs=False))
        roots = autoreload.common_roots(self.watched_roots(watched_files))
        watcher = watchfiles.watch(*roots, debug=True)
        pprint(roots)
        sys.exit()
        for file_changes in watcher:
            for _change, path in file_changes:
                self.notify_file_changed(Path(path))
            yield


def replaced_get_reloader() -> autoreload.BaseReloader:
    return WatchfilesReloader()


autoreload.get_reloader = replaced_get_reloader
```
</details>

<details>
<summary>Output : </summary>

```shell
Performing system checks...

System check identified no issues (0 silenced).

You have 42 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, anime, auth, characters, contenttypes, producers, sessions, staffs, studios, trackers, user.
Run 'python manage.py migrate' to apply them.
January 03, 2023 - 16:28:05
Django version 4.1.4, using settings 'core.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
(WindowsPath('C:/Users/Asus/.virtualenvs/backend-mFRfaiMD'),
 WindowsPath('C:/Users/Asus/AppData/Local/Programs/Python/Python311'),
 WindowsPath('C:/Users/Asus/Downloads/CoreProject-540f8e030cf54a865c962bd7e886b76948ccb65c/backend/django_core'),
 WindowsPath('C:/Users/Asus/Downloads/CoreProject-540f8e030cf54a865c962bd7e886b76948ccb65c/backend/locale'))
```

</details>

**Comment by adamchainz** [comment]
Which of those paths is "neither a file nor a directory" ? They all look like they could be directories to me. PErhaps one doesn't actually exist? Or is a link?

**Comment by baseplate-admin** [comment]
> Which of those paths is "neither a file nor a directory" ? They all look like they could be directories to me. PErhaps one doesn't actually exist? Or is a link?

Seems to me all the files are actually valid. Django's reloader works normally as expected

**Comment by joshuadavidthomas** [comment]
I was running into this too, and in the process of doing some quick print debugging, I found the root issue: the `extra_directories` included a bunch of non-existent folders related to i18n within my project:

```python
def watched_roots(self, watched_files: list[Path]) -> frozenset[Path]:
    extra_directories = self.directory_globs.keys()
    for path in extra_directories:
        print("Checking path", path)
    watched_file_dirs = {f.parent for f in watched_files}
    sys_paths = set(autoreload.sys_path_directories())
    return frozenset((*extra_directories, *watched_file_dirs, *sys_paths))
```

```python
Checking path /home/josh/projects/dbbackup/dbbackup/templates
Checking path /home/josh/.pyenv/versions/dbbackup-3.11.4/lib/python3.11/site-packages/health_check/templates
Checking path /home/josh/.pyenv/versions/dbbackup-3.11.4/lib/python3.11/site-packages/simple_history/templates
Checking path /home/josh/.pyenv/versions/dbbackup-3.11.4/lib/python3.11/site-packages/tailwind/templates
Checking path /home/josh/.pyenv/versions/dbbackup-3.11.4/lib/python3.11/site-packages/debug_toolbar/templates
Checking path /home/josh/.pyenv/versions/dbbackup-3.11.4/lib/python3.11/site-packages/allauth/templates
Checking path /home/josh/.pyenv/versions/dbbackup-3.11.4/lib/python3.11/site-packages/django_extensions/templates
Checking path /home/josh/projects/dbbackup/locale
Checking path /home/josh/.pyenv/versions/dbbackup-3.11.4/lib/python3.11/site-packages/debug_toolbar/locale
Checking path /home/josh/.pyenv/versions/dbbackup-3.11.4/lib/python3.11/site-packages/whitenoise/runserver_nostatic/locale
Checking path /home/josh/projects/dbbackup/dbbackup/core/locale
Checking path /home/josh/projects/dbbackup/dbbackup/flydb/locale
Checking path /home/josh/projects/dbbackup/dbbackup/tasks/locale
Checking path /home/josh/projects/dbbackup/dbbackup/theme/locale
Checking path /home/josh/projects/dbbackup/dbbackup/users/locale
...
```

I traced it down to what I think is a bug within the `BaseReloader` itself and have opened a ticket to address it - [#34720](https://code.djangoproject.com/ticket/34720).

**Comment by joshuadavidthomas** [comment]
Per @felixxm on [review](https://github.com/django/django/pull/17088#discussion_r1266192868):

> It was not crucial for this method to check if the path exists. We added try ... except to avoid crashes related with an issue in Python run on some Docker images (check out ticket-30647), IMO it's still not fixed. watch_dir() is used in watch_for_translation_changes() to watch all potential directories, so actually checking exists() may not be desirable.

Given the error, I think watchfiles expects the files/folders it's watching to exist, so `watched_roots` may need to be adjusted to take this in to account. Willing to open a PR to work on this, if wanted.

**Comment by adamchainz** [comment]
A PR would be welcome. I would also like to get some tests working, if you have the time for that.

**Comment by kissgyorgy** [comment]
Hello,
I hit the same error. Sadly Django puts wired-in dirs into the `self.directory_globs`, specifically `locale` dirs if I18N is enabled: https://github.com/django/django/blob/b8b2f7451201f3ff60891b6ce55f177400700d7a/django/utils/translation/reloader.py#L13-L14

I think the sensible thing to do is to just exclude non-existing dirs, something like this:

```diff
    def watched_roots(self, watched_files: list[Path]) -> frozenset[Path]:
        extra_directories = self.directory_globs.keys()
        watched_file_dirs = {f.parent for f in watched_files}
        sys_paths = set(autoreload.sys_path_directories())
-       return frozenset((*extra_directories, *watched_file_dirs, *sys_paths))
+       all_dirs = (*extra_directories, *watched_file_dirs, *sys_paths)
+       existing_dirs = (p for p in all_dirs if p.exists())
+       return frozenset(existing_dirs)
```
